name: jaguar_query
description: Dialect neutral, fluent Dart DSL to build SQL/NoSQL queries
version: 0.0.3
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  meta: '>=1.0.4 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  jaguar_orm_postgresql:
    git: https://github.com/Jaguar-dart/jaguar_orm_postgresql.git
